language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key: 79368ebf-23a9-4b4d-9918-7acfe9ca7dc6
  app: react-trello-testing
  on:
    repo: jkathan/react-trello-testing
